using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MCDynamite.Net
{
    public class Packets
    {
        public byte KeepAlive = 0x00;
        public byte LoginRequest = 0x01;
        public byte Handshake = 0x02;
        public byte ChatMessage = 0x03;
        public byte TimeUpdate = 0x04;
        public byte EntityEquipment = 0x05;
        public byte SpawnPosition = 0x06;
        public byte UseEntity = 0x07;
        public byte UpdateHealth = 0x08;
        public byte Respawn = 0x09;
        public byte Player = 0x0A;
        public byte PlayerPosition = 0x0B;
        public byte PlayerLook = 0x0C;
        public byte PlayerPositionLook = 0x0D;
        public byte PlayerDigging = 0x0E;
        public byte PlayerBlockPlacement = 0x0F;
        public byte HeldItemChange = 0x10;
        public byte UseBed = 0x11;
        public byte Animation = 0x12;
        public byte EntityAction = 0x13;
        public byte SpawnNamedEntity = 0x14;
        public byte CollectItem = 0x16;
        public byte SpawnVehicle = 0x17;
        public byte SpawnMob = 0x18;
        public byte SpawnPainting = 0x19;
        public byte SpawnExperienceOrb = 0x1A;
        public byte EntityVelocity = 0x1C;
        public byte DestroyEntity = 0x1D;
        public byte Entity = 0x1E;
        public byte EntityRelativeMove = 0x1F;
        public byte EntityLook = 0x20;
        public byte EntityLookRelativeMove = 0x21;
        public byte EntityTeleport = 0x22;
        public byte EntityHeadLook = 0x23;
        public byte EntityStatus = 0x26;
        public byte AttachEntity = 0x27;
        public byte EntityMetadata = 0x28;
        public byte EntityEffect = 0x29;
        public byte RemoveEntityEffect = 0x2A;
        public byte SetExperience = 0x2B;
        public byte ChunkData = 0x33;
        public byte MultiBlockChange = 0x34;
        public byte BlockChange = 0x35;
        public byte BlockAction = 0x36;
        public byte BlockBreakAnimation = 0x37;
        public byte MapChunkBulk = 0x38;
        public byte Explosion = 0x3C;
        public byte SoundParticleEffect = 0x3D;
        public byte NamedSoundEffect = 0x3E;
        public byte Particle = 0x3F;
        public byte ChangeGameState = 0x46;
        public byte SpawnGlobalEntity = 0x47;
        public byte OpenWindow = 0x64;
        public byte CloseWindow = 0x65;
        public byte ClickWindow = 0x66;
        public byte SetSlot = 0x67;
        public byte SetWindowItems = 0x68;
        public byte UpdateWindowProperty = 0x69;
        public byte ConfirmTransaction = 0x6A;
        public byte CreativeInventoryAction = 0x6B;
        public byte EnchantItem = 0x6C;
        public byte UpdateSign = 0x82;
        public byte ItemData = 0x83;
        public byte UpdateTileEntity = 0x84;
        public byte IncrementStatistic = 0xC8;
        public byte PlayerListItem = 0xC9;
        public byte PlayerAbilities = 0xCA;
        public byte TabComplete = 0xCB;
        public byte ClientSettings = 0xCC;
        public byte ClientStatuses = 0xCD;
        public byte ScoreboardObjective = 0xCE;
        public byte UpdateScore = 0xCF;
        public byte DisplayScoreboard = 0xD0;
        public byte Teams = 0xD1;
        public byte PluginMessage = 0xFA;
        public byte EncryptionKeyResponse = 0xFC;
        public byte EncryptionKeyRequest = 0xFD;
        public byte ServerListPing = 0xFE;
        public byte Kick = 0xFF;
    }
}
