using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MCDynamite.Net
{
    public class Packets
    {
        public const byte KeepAlive = 0x00;
        public const byte LoginRequest = 0x01;
        public const byte Handshake = 0x02;
        public const byte ChatMessage = 0x03;
        public const byte TimeUpdate = 0x04;
        public const byte EntityEquipment = 0x05;
        public const byte SpawnPosition = 0x06;
        public const byte UseEntity = 0x07;
        public const byte UpdateHealth = 0x08;
        public const byte Respawn = 0x09;
        public const byte Player = 0x0A;
        public const byte PlayerPosition = 0x0B;
        public const byte PlayerLook = 0x0C;
        public const byte PlayerPositionLook = 0x0D;
        public const byte PlayerDigging = 0x0E;
        public const byte PlayerBlockPlacement = 0x0F;
        public const byte HeldItemChange = 0x10;
        public const byte UseBed = 0x11;
        public const byte Animation = 0x12;
        public const byte EntityAction = 0x13;
        public const byte SpawnNamedEntity = 0x14;
        public const byte CollectItem = 0x16;
        public const byte SpawnVehicle = 0x17;
        public const byte SpawnMob = 0x18;
        public const byte SpawnPainting = 0x19;
        public const byte SpawnExperienceOrb = 0x1A;
        public const byte EntityVelocity = 0x1C;
        public const byte DestroyEntity = 0x1D;
        public const byte Entity = 0x1E;
        public const byte EntityRelativeMove = 0x1F;
        public const byte EntityLook = 0x20;
        public const byte EntityLookRelativeMove = 0x21;
        public const byte EntityTeleport = 0x22;
        public const byte EntityHeadLook = 0x23;
        public const byte EntityStatus = 0x26;
        public const byte AttachEntity = 0x27;
        public const byte EntityMetadata = 0x28;
        public const byte EntityEffect = 0x29;
        public const byte RemoveEntityEffect = 0x2A;
        public const byte SetExperience = 0x2B;
        public const byte ChunkData = 0x33;
        public const byte MultiBlockChange = 0x34;
        public const byte BlockChange = 0x35;
        public const byte BlockAction = 0x36;
        public const byte BlockBreakAnimation = 0x37;
        public const byte MapChunkBulk = 0x38;
        public const byte Explosion = 0x3C;
        public const byte SoundParticleEffect = 0x3D;
        public const byte NamedSoundEffect = 0x3E;
        public const byte Particle = 0x3F;
        public const byte ChangeGameState = 0x46;
        public const byte SpawnGlobalEntity = 0x47;
        public const byte OpenWindow = 0x64;
        public const byte CloseWindow = 0x65;
        public const byte ClickWindow = 0x66;
        public const byte SetSlot = 0x67;
        public const byte SetWindowItems = 0x68;
        public const byte UpdateWindowProperty = 0x69;
        public const byte ConfirmTransaction = 0x6A;
        public const byte CreativeInventoryAction = 0x6B;
        public const byte EnchantItem = 0x6C;
        public const byte UpdateSign = 0x82;
        public const byte ItemData = 0x83;
        public const byte UpdateTileEntity = 0x84;
        public const byte IncrementStatistic = 0xC8;
        public const byte PlayerListItem = 0xC9;
        public const byte PlayerAbilities = 0xCA;
        public const byte TabComplete = 0xCB;
        public const byte ClientSettings = 0xCC;
        public const byte ClientStatuses = 0xCD;
        public const byte ScoreboardObjective = 0xCE;
        public const byte UpdateScore = 0xCF;
        public const byte DisplayScoreboard = 0xD0;
        public const byte Teams = 0xD1;
        public const byte PluginMessage = 0xFA;
        public const byte EncryptionKeyResponse = 0xFC;
        public const byte EncryptionKeyRequest = 0xFD;
        public const byte ServerListPing = 0xFE;
        public const byte Kick = 0xFF;
    }
}
