using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MCDynamite.Net
{
    public class Packets {	
	public static const byte KeepAlive = (byte) 0x00;
	public static const byte LoginRequest = (byte) 0x01;
	public static const byte Handshake = (byte) 0x02;
	public static const byte ChatMessage = (byte) 0x03;
	public static const byte TimeUpdate = (byte) 0x04;
	public static const byte EntityEquipment = (byte) 0x05;
	public static const byte SpawnPosition = (byte) 0x06;
	public static const byte UseEntity = (byte) 0x07;
	public static const byte UpdateHealth = (byte) 0x08;
	public static const byte Respawn = (byte) 0x09;
	public static const byte Player = (byte) 0x0A;
	public static const byte PlayerPosition = (byte) 0x0B;
	public static const byte PlayerLook = (byte) 0x0C;
	public static const byte PlayerPositionLook = (byte) 0x0D;
	public static const byte PlayerDigging = (byte) 0x0E;
	public static const byte PlayerBlockPlacement = (byte) 0x0F;
	public static const byte HeldItemChange = (byte) 0x10;
	public static const byte UseBed = (byte) 0x11;
	public static const byte Animation = (byte) 0x12;
	public static const byte EntityAction = (byte) 0x13;
	public static const byte SpawnNamedEntity = (byte) 0x14;
	public static const byte CollectItem = (byte) 0x16;
	public static const byte SpawnVehicle = (byte) 0x17;
	public static const byte SpawnMob = (byte) 0x18;
	public static const byte SpawnPainting = (byte) 0x19;
	public static const byte SpawnExperienceOrb = (byte) 0x1A;
	public static const byte EntityVelocity = (byte) 0x1C;
	public static const byte DestroyEntity = (byte) 0x1D;
	public static const byte Entity = (byte) 0x1E;
	public static const byte EntityRelativeMove = (byte) 0x1F;
	public static const byte EntityLook = (byte) 0x20;
	public static const byte EntityLookRelativeMove = 0x21;
	public static const byte EntityTeleport = (byte) 0x22;
	public static const byte EntityHeadLook = (byte) 0x23;
	public static const byte EntityStatus = (byte) 0x26;
	public static const byte AttachEntity = (byte) 0x27;
	public static const byte EntityMetadata = (byte) 0x28;
	public static const byte EntityEffect = (byte) 0x29;
	public static const byte RemoveEntityEffect = (byte) 0x2A;
	public static const byte SetExperience = (byte) 0x2B;
	public static const byte ChunkData = (byte) 0x33;
	public static const byte MultiBlockChange = (byte) 0x34;
	public static const byte BlockChange = (byte) 0x35;
	public static const byte BlockAction = (byte) 0x36;
	public static const byte BlockBreakAnimation = (byte) 0x37;
	public static const byte MapChunkBulk = (byte) 0x38;
	public static const byte Explosion = (byte) 0x3C;
	public static const byte SoundParticleEffect = (byte) 0x3D;
	public static const byte NamedSoundEffect = (byte) 0x3E;
	public static const byte Particle = (byte) 0x3F;
	public static const byte ChangeGameState = (byte) 0x46;
	public static const byte SpawnGlobalEntity = (byte) 0x47;
	public static const byte OpenWindow = (byte) 0x64;
	public static const byte CloseWindow = (byte) 0x65;
	public static const byte ClickWindow = (byte) 0x66;
	public static const byte SetSlot = (byte) 0x67;
	public static const byte SetWindowItems = (byte) 0x68;
	public static const byte UpdateWindowProperty = (byte) 0x69;
	public static const byte ConfirmTransaction = (byte) 0x6A;
	public static const byte CreativeInventoryAction = (byte) 0x6B;
	public static const byte EnchantItem = (byte) 0x6C;
	public static const byte UpdateSign = (byte) 0x82;
	public static const byte ItemData = (byte) 0x83;
	public static const byte UpdateTileEntity = (byte) 0x84;
	public static const byte IncrementStatistic = (byte) 0xC8;
	public static const byte PlayerListItem = (byte) 0xC9;
	public static const byte PlayerAbilities = (byte) 0xCA;
	public static const byte TabComplete = (byte) 0xCB;
	public static const byte ClientSettings = (byte) 0xCC;
	public static const byte ClientStatuses = (byte) 0xCD;
	public static const byte ScoreboardObjective = (byte) 0xCE;
	public static const byte UpdateScore = (byte) 0xCF;
	public static const byte DisplayScoreboard = (byte) 0xD0;
	public static const byte Teams = (byte) 0xD1;
	public static const byte PluginMessage = (byte) 0xFA;
	public static const byte EncryptionKeyResponse = (byte) 0xFC;
	public static const byte EncryptionKeyRequest = (byte) 0xFD;
	public static const byte ServerListPing = (byte) 0xFE;
	public static const byte Kick = (byte) 0xFF;
}
